title: Cristiano Leopardi MadFolio
description: Benvenuto, sono Cristiano e questo è il mio portfolio, qui desidero condividere tutte le mie esperienze professionali e di vita create durante la mia carriera professionale e non



baseurl: "/madfolio.github.io" # the subpath of your site, e.g. /blog
url: "https://madfolio.github.io" # the base hostname & protocol for your site
permalink: /:title/


compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


analytics: 

color-1: '#e74c3c'
color-2: '##1abc9c'
color-3: '##1abc9c'
color-4: '##1abc9c'
color-5: '##1abc9c'
color-6: '##1abc9c'
color-7: '##1abc9c'
color-8: '##1abc9c'
